import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { getServerSession } from "next-auth";
import { NextAuthProvider } from "./providers";
import { CookiesProvider } from "next-client-cookies/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  console.log(session);

  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <CookiesProvider>
            {!!session && <Navbar />}
            {!session && <Navbar />}
            <div className="container h-full pt-12">{children}</div>
          </CookiesProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
